### ISSUE TITLE
Test servers detailed information?

### ISSUE THREAD

**Issue by yunhua-lee** [shuveb/zerohttpd#4]
I read the article from https://unixism.net/2019/04/linux-applications-performance-introduction/ and I did not find the detailed  information for test servers. The article only said " all servers have a single CPU core".  Would you please supplement the detailed information including memory, network bandwidth, disk, and so on ?
Thanks a lot.

**Comment by shuveb** [comment]
Hello,

This was a single core server as offered by Digital Ocean.

Thanks,
Shuveb
